version: '3'

services:
    web:
        build: .
        command: python -u flask_brevets.py
        #command: sleep infinity
        ports:
            - "5973:5000"
        depends_on:
            - ourdb
        environment:
            MONGODB_HOSTNAME: ourdb
    ourdb:
        image: mongo:latest
